### ISSUE TITLE
S3 code w/ jQuery wrapper not working with 5.11.4 Amazon S3 package (Uncaught TypeError)

### ISSUE THREAD

**Issue by smcoll** [FineUploader/fine-uploader#1643]
bug / S3 / 5.11.4 / Chromium / Ubuntu 16.04

i'm just trying to get a working example of the S3 implementation, by starting with the S3 demo source and the latest S3 package.  i may be missing something in the implementation. 

1. Download the 5.11.4 Amazon S3 package
2. Copy the html of the S3 jquery demo from http://fineuploader.com/demos.html#amazon-demo
3. Replace some variables in the script, including pointing to the downloaded files
4. Load the page in a browser

When the page loads, it is blank, and the console logs: `Uncaught TypeError: $(...).fineUploaderS3 is not a function`.

i can confirm that all the resources (`jquery.min.js`, `fine-uploader-gallery.css`, `s3.jquery.fine-uploader.js`) are loading properly (via developer tools).  `fineUploader` is recognized as a valid function in jquery, but `fineUploaderS3` is not.  

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- jQuery
    ====================================================================== -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

    <!-- Fine Uploader Gallery CSS file
    ====================================================================== -->
    <link href="/static/fine-uploader/fine-uploader-gallery.css" rel="stylesheet">

    <!-- Fine Uploader S3 jQuery JS file
    ====================================================================== -->
    <script src="/static/fine-uploader/s3.jquery.fine-uploader.js"></script>

    <!-- Fine Uploader Customized Gallery template
    ====================================================================== -->
    <script type="text/template" id="qq-template-s3">
        <div class="qq-uploader-selector qq-uploader qq-gallery" qq-drop-area-text="Drop files here">
            <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
                <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
            </div>
            <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
                <span class="qq-upload-drop-area-text-selector"></span>
            </div>
            <div class="qq-upload-button-selector qq-upload-button">
                <div>Upload a file</div>
            </div>
            <span class="qq-drop-processing-selector qq-drop-processing">
                <span>Processing dropped files...</span>
                <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
            </span>
            <ul class="qq-upload-list-selector qq-upload-list" role="region" aria-live="polite" aria-relevant="additions removals">
                <li>
                    <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
                    <div class="qq-progress-bar-container-selector qq-progress-bar-container">
                        <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
                    </div>
                    <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                    <div class="qq-thumbnail-wrapper">
                        <a class="preview-link" target="_blank">
                            <img class="qq-thumbnail-selector" qq-max-size="120" qq-server-scale>
                        </a>
                    </div>
                    <button type="button" class="qq-upload-cancel-selector qq-upload-cancel">X</button>
                    <button type="button" class="qq-upload-retry-selector qq-upload-retry">
                        <span class="qq-btn qq-retry-icon" aria-label="Retry"></span>
                        Retry
                    </button>

                    <div class="qq-file-info">
                        <div class="qq-file-name">
                            <span class="qq-upload-file-selector qq-upload-file"></span>
                            <span class="qq-edit-filename-icon-selector qq-edit-filename-icon" aria-label="Edit filename"></span>
                        </div>
                        <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                        <span class="qq-upload-size-selector qq-upload-size"></span>
                        <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">
                            <span class="qq-btn qq-delete-icon" aria-label="Delete"></span>
                        </button>
                        <button type="button" class="qq-btn qq-upload-pause-selector qq-upload-pause">
                            <span class="qq-btn qq-pause-icon" aria-label="Pause"></span>
                        </button>
                        <button type="button" class="qq-btn qq-upload-continue-selector qq-upload-continue">
                            <span class="qq-btn qq-continue-icon" aria-label="Continue"></span>
                        </button>
                    </div>
                </li>
            </ul>

            <dialog class="qq-alert-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">Close</button>
                </div>
            </dialog>

            <dialog class="qq-confirm-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">No</button>
                    <button type="button" class="qq-ok-button-selector">Yes</button>
                </div>
            </dialog>

            <dialog class="qq-prompt-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <input type="text">
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">Cancel</button>
                    <button type="button" class="qq-ok-button-selector">Ok</button>
                </div>
            </dialog>
        </div>
    </script>

    <style>
        #fine-uploader-s3 .preview-link {
            display: block;
            height: 100%;
            width: 100%;
        }
    </style>

    <title>Fine Uploader S3 Demo</title>
</head>
<body>
    <!-- Fine Uploader DOM Element
    ====================================================================== -->
    <div id="fine-uploader-s3"></div>

    <!-- Your code to create an instance of Fine Uploader and bind to the DOM/template
    ====================================================================== -->
    <script>
        $('#fine-uploader-s3').fineUploaderS3({  
            template: 'qq-template-s3',
            request: {
                endpoint: "REDACTED",
                accessKey: "REDACTED"
            },
            signature: {
                endpoint: "//localhost:8000/upload-handler/"
            },
            uploadSuccess: {
                endpoint: "//localhost:8000/callbacks/s3/",  <!-- obviously, this won't work locally -->
                params: {
                    isBrowserPreviewCapable: qq.supportedFeatures.imagePreviews
                }
            },
            iframeSupport: {
                localBlankPagePath: "//localhost:8000/upload-handler/blank"
            },
            cors: {
                expected: true
            },
            chunking: {
                enabled: true
            },
            resume: {
                enabled: true
            },
            validation: {
                itemLimit: 5,
                sizeLimit: 15000000
            },
            thumbnails: {
                placeholders: {
                    notAvailablePath: "/static/fine-uploader/placeholders/not_available-generic.png",
                    waitingPath: "/static/fine-uploader/placeholders/waiting-generic.png"
                }
            },
            callbacks: {
                onComplete: function(id, name, response) {
                    var previewLink = qq(this.getItemByFileId(id)).getByClass('preview-link')[0];

                    if (response.success) {
                        previewLink.setAttribute("href", response.tempLink)
                    }
                }
            }
        });
    </script>
</body>
</html>

```

**Comment by rnicholus** [comment]
Thanks for the report, and I can confirm that this is a bug introduced by the build refactor in 5.11.0. It likely affects Fine Uploader S3 and Azure jQuery wrappers. The jQuery wrappers are not well tested anymore, which is why there have been a few regressions related to these wrappers recently. I plan to remove the wrappers entirely in 6.0 since there is really no benefit provided by jQuery wrappers in the case of Fine Uploader.

There are a couple workarounds until I fix this in 5.11.4:

- Temporarily move back to 5.10.1
- Stop using the jQuery wrapper. You can still use jQuery in your project, if you wish, but there is no real benefit to wrapping Fine Uploader w/ jQuery. More info at #1310.

**Comment by smcoll** [comment]
@rnicholus i really appreciate your timely response.  Using the non-jquery version fixes the issue for me.

**Comment by rnicholus** [comment]
Fixed in 5.11.5, [released today](https://github.com/FineUploader/fine-uploader/releases/tag/5.11.5).
